### ISSUE TITLE
typesetting error in combination with tablefootnote (reledmac v. 2.2.2)

### ISSUE THREAD

**Issue by mxordn** [maieul/ledmac#423] opened 2015-10-13 16:57 UTC
Dear Maïeul,

after updating after updating from reledmac 2.2.0 to 2.2.2 (TeXLive 2015) I currently get lots of errors pointing to reledmac.sty when typesetting the following MWE:

```\documentclass[11pt,a4paper,BCOR=12mm,DIV=14]{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{typearea}

%Fußnoten in Tabellen
\usepackage{tablefootnote}
\makeatletter
\newcommand{\spewfootnotes}{%
\tfn@tablefootnoteprintout%
\global\let\tfn@tablefootnoteprintout\relax%
\gdef\tfn@fnt{0}%
}
\makeatother


\usepackage{hyperref}
\usepackage{imakeidx}
\usepackage{reledmac}
\usepackage{reledpar}


\begin{document}
\begin{tabular}{l l}
Hallo Welt! & Blubb\tablefootnote{Fußnote}\\
\end{tabular}
\spewfootnotes
\end{document}
```

I think it has to do with the `tablefootnote` code. If you load `reledmac` before `tablefootnote` everything runs as expected. I just wanted to let you know this, because these errors that can't be ignored by latex and occured never before the update to version 2.2.2 (from 2.2.0). As I don't know, if this might have greater impact on other packages as well, maybe this issue could be closed immediately.

Best Regards
Moritz

**Comment by maieul** [comment] 2015-10-13 17:33
Could I have the results of a \listfiles ? and the precise message error ? I don't have any error for me. I suppose it is related to "no room for newskip". I thinks it is related to the changes required by the last version of LaTeX, and proposed by @davidcarlisle.


Also say which class is used and the .logs

**Comment by davidcarlisle** [comment] 2015-10-13 19:33
If I add `\documentclass{article}` to the posted code and run with pdflatex I get

```
! You can't use a prefix with `\begingroup'.
<to be read again> 
                   \begingroup 
l.3853 ...r\newseries\expandafter{\default@series}
```

is that the error you see?

(ignore any errors after that, they will be spurious)

Not sure why yet, looking....

**Comment by davidcarlisle** [comment] 2015-10-13 19:55
the issue is really xifthen package which unconditionally loads etex.sty, it would be better if it did not (and if you comment out `%\RequirePackage{etex}` in a local copy it all works. I'll contact the author.

That said it would probably be better if it didn't error, or if it gave a more sensible error, I'll see if I can cut the example down a bit and make a specific test case.

It does not look like reldmac is to blame this time:-)

**Comment by mxordn** [comment] 2015-10-13 20:42
Thanks a lot for your ideas and help. If yet still necessary, you'll find my logfile and my test-files over here:

https://www.dropbox.com/sh/3fch3hcfsgjxg22/AADfGkIure0BrXR9YUq8UgwBa?dl=0

My first error is:

/usr/local/texlive/2015/texmf-dist/tex/latex/reledmac/reledmac.sty:3854: No roo
m for a new \count .
\ch@ck ...\else \errmessage {No room for a new #3}
                                                  \fi 
l.3854 ...r\newseries\expandafter{\default@series}

But maybe it's already all clear :).



Am 13.10.2015 um 21:55 schrieb David Carlisle <notifications@github.com>:

**Comment by maieul** [comment] 2015-10-14 07:56
I am quite glad to have no more to modify reledmac ;-)

**Comment by maieul** [comment] 2015-10-14 08:46
oh, I undertsand why I didn't get the bug. It is only with pdflatex, not with xelatex.

**Comment by maieul** [comment] 2015-10-14 09:46
I close this issue, as it is related to xifthen package, and as the maintener of this package said he will correct it in one week.

**Closed by maieul** 2015-10-14 09:46 UTC
