### ISSUE TITLE
Empty paragraphs and line numbers

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#311] opened 2015-05-18 07:05 UTC
If in eledpar, one paragraph is empty, the last line number is in the wrong place. Check the example.

```\listfiles
\documentclass{book}
\usepackage[english]{babel} 
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{blindtext}
\usepackage[noeledsec,noend,series={A},noledgroup]{eledmac}
\usepackage{eledpar}
\begin{document}
Check page 2, the line number of line 17 is in the wrong place. If you go back into this \TeX{} file and uncomment line 27, you are going to find the line number on the correct spot.

%\newpage
\begin{pages}
\begin{Leftside}
\beginnumbering
\linenumincrement{1}
\firstlinenum{1}
\pstart[%
\section{Das erste Kapitel}%
\subsection{Der erste Abschnitt}]

Der Originaltext: \blindtext[2] Ja, das ist er!
\pend

\pstart
%%%Dieses Stück fehlt hier!
%{\ }%
\skipnumbering{}
\pend

\pstart[\subsection{Der zweite Abschnitt}]

Der Originaltext: \blindtext[2] Ja, das ist er!
\pend
\endnumbering   
\end{Leftside}

\begin{Rightside}
\beginnumbering
\linenumincrement{1}
\firstlinenum{1}
\pstart[%
\section{Das erste Kapitel}%
\subsection{Der erste Abschnitt}]

Der übersetzte Tex, das ist er! \blindtext[3]
\pend

\pstart
Ein kurzes Stück, das drüben fehlt!
\pend

\pstart[\subsection{Der zweite Abschnitt}]

Der übersetzte Text, das ist er! \blindtext[2]
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

Now you may ask: Why empty paragraphs? The problem arose in the context of a comparison of a biblical papyrus, where on the left pages is the papyrus, and on the right page the standard text. As the papyrus has an incomplete text, some paragraphs have to stay empty ...

**Comment by maieul** [comment] 2015-05-18 08:37
please try branch issue311. 

Notes that your problem was not this. The problem is 1) with skipnumbering 2) immediatly after a pstart.

**Comment by baem2** [comment] 2015-05-18 15:58
Okay, thanks for clarification. issue311 leads to an error for me:

```! TeX capacity exceeded, sorry [input stack size=5000].
\skipnumbering ->\skipnumbering 
                                \ifledRcol \ifinstanza \write \linenum@outR ...
l.4870 ...relax\noexpand&\leavevmode\skipnumbering
                                                  }
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.```

**Comment by maieul** [comment] 2015-05-18 16:03
there was a mist pastebin. try new version just send now

**Comment by baem2** [comment] 2015-05-18 16:09
Fix confirmed, thanks!

**Comment by maieul** [comment] 2015-05-18 16:11
ok, merged to the feature branch




Le 18 mai 2015 � 18:09, Philipp <notifications@github.com> a �crit :

**Closed** 2015-05-18 20:00 UTC
