### ISSUE TITLE
indexing: xindy ignores indexentry in linenumber 5

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#298] opened 2015-05-06 09:53 UTC
In numbered text Xindy does ignore, as it seems, the first indexentry (\indexentry{entry|eledmac5}{x-y} in a line, which becomes the fifth line of the pdf-output. The warning is: unknown attribute 'eledmac5'! (ignored).
When more than one \edindex-command are placed in the latter line 5, only the first will be ignored. 

\documentclass{scrbook}

\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{german}

\usepackage[xindy,splitindex]{indextools}%On précise qu'on veut utiliser xindy + splitindex
\indexsetup{level=\section*,toclevel=section,noclearpage,othercode=\footnotesize}
\usepackage[series={A},noeledsec,nofamiliar,noend,xindy,xindy+hyperref]{eledmac}
\usepackage[hyperindex=false]{hyperref}

\makeindex[name=verb,intoc=true,title=Index verborum]

\begin{document}

\beginnumbering
\pstart
In principio\edindex[verb]{principium} erat verbum et verbum\edindex[verb]{verbum} erat apud Deum et Deus erat verbum, hoc erat in principio apud Deum. Omnia per ipsum facta sunt, et sine ipso factum est nihil\edindex[verb]{nihil}. Quod factum est in ipso vita erat, et vita erat lux hominum. Et lux\edindex[verb]{lux} in tenebris lucet, et tenebrae eam non comprehenderunt.
\pend
\pstart
Fuit homo\edindex[verb]{homo} missus a Deo\edindex[verb]{deus} cui nomen Johannes. Hic venit in testimonium ut testimonium perhiberet de lumine ut omnes crederent per illum. Non erat ille lux, sed ut testimonium perhiberet de lumine. Erat lux vera quae illuminat omnem hominem venientem in hunc mundum\edindex[verb]{mundus}, in mundo erat et mundus per ipsum factus est et mundus eum non cognovit.
\pend
\endnumbering

\printindex[verb]

\end{document}

**Comment by maieul** [comment] 2015-05-06 13:19
why do you do 

`\usepackage[xindy,splitindex]{indextools}` ? xindy is not compatible with splitindex. In any case I have to look more.

**Comment by maieul** [comment] 2015-05-06 13:37
With this preamble

`````
\usepackage[xindy,noautomatic]{indextools}%On précise qu'on veut utiliser xindy

\usepackage[series={A},noeledsec,nofamiliar,noend,xindy,xindy+hyperref]{eledmac}
\usepackage[hyperindex=false]{hyperref}

\makeindex[name=verb,intoc=true,title=Index verborum]
\indexsetup{level=\section*,toclevel=section,othercode=\footnotesize}
`````
all works.

However with `\indexsetup{level=\section*,toclevel=section,noclearpage,othercode=\footnotesize}` the .idx file is not correctly writed. The problem is not linked to eledmac but to indextools. 

Cf this MWE

`````
\documentclass{book}

\usepackage{fontspec}


\usepackage[]{indextools}%On précise qu'on veut utiliser xindy

\makeindex[name=verb,intoc=true,title=Index verborum]
\indexsetup{level=\section*,toclevel=section,noclearpage,othercode=\footnotesize}
\begin{document}


\index[verb]{toto}
s

 \printindex[verb]

 \end{document}
````

**Comment by maieul** [comment] 2015-05-06 13:40
````
\documentclass{book}

\usepackage{fontspec}


\usepackage[]{indextools}%On précise qu'on veut utiliser xindy

\makeindex[name=verb,intoc=true,title=Index verborum]
\indexsetup{level=\section*,toclevel=section,noclearpage,othercode=\footnotesize}
\begin{document}


\index[verb]{toto}
s
\newpage
 \printindex[verb]

 \end{document}
````

**Comment by maieul** [comment] 2015-05-06 13:40
this last example work.

**Comment by maieul** [comment] 2015-05-06 13:49
So

````
\documentclass{scrbook}

\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{german}

\usepackage[xindy]{indextools}%On précise qu'on veut utiliser xindy + splitindex
\indexsetup{level=\section*,toclevel=section,noclearpage,othercode=\footnotesize}
\usepackage[series={A},noeledsec,nofamiliar,noend,xindy,xindy+hyperref]{eledmac}
\usepackage[hyperindex=false]{hyperref}

\makeindex[name=verb,intoc=true,title=Index verborum]

\begin{document}

\beginnumbering
\pstart
In principio\edindex[verb]{principium} erat verbum et verbum\edindex[verb]{verbum} erat apud Deum et Deus erat verbum, hoc erat in principio apud Deum. Omnia per ipsum facta sunt, et sine ipso factum est nihil\edindex[verb]{nihil}. Quod factum est in ipso vita erat, et vita erat lux hominum. Et lux\edindex[verb]{lux} in tenebris lucet, et tenebrae eam non comprehenderunt.
\pend
\pstart
Fuit homo\edindex[verb]{homo} missus a Deo\edindex[verb]{deus} cui nomen Johannes. Hic venit in testimonium ut testimonium perhiberet de lumine ut omnes crederent per illum. Non erat ille lux, sed ut testimonium perhiberet de lumine. Erat lux vera quae illuminat omnem hominem venientem in hunc mundum\edindex[verb]{mundus}, in mundo erat et mundus per ipsum factus est et mundus eum non cognovit.
\pend
\endnumbering

\newpage
\printindex[verb]

\end{document}
`````
works perfectly.

**Comment by sonator** [comment] 2015-05-06 16:17
Sorry, at the moment I am somewhat confused. 

My MWE is an extract of a test file with four indizes. I thought that it would be possible to use the splitindex option of indextools, as described on page 4 of the documentation. And the first tests were successfull, but then an entry in line 5 was ignored by xindy. 

Now, your modified example (without splitindex option) causes the same xindy warning. The idx-file created by xelatex seems to be okay. But xindy ignores one of seven entries, namely the first one in line 5 (homo) specified by 'eledmac5' in the idx-file, presumably a problem of my system (Win 7, MikTeX). 

I try to find a solution. Thank you for your tests!

**Comment by maieul** [comment] 2015-05-06 16:24
xindy need to read a .idx file with standard format. file with splindex, you have not it. So tha mean you 
1) first run splitindex on the main .idx
2) then run xindiy on the new .idx generate by splitindex.

However, that as nothing to do with your problem, as the change proves.

When you call texindy, do you call the xdy files produces by latex?

What is the content of this file ?

could you explain more the xindy error?

**Comment by maieul** [comment] 2015-05-06 16:26
please send my your 
1) .idx file 
2) .xdy file generated by eledmac.

Without that, I can't do anything

**Comment by sonator** [comment] 2015-05-06 16:34
I couldn't attach the files itself. These are the contents.

The idx-file: 
\indexentry{principium|eledmac1}{1-1}
\indexentry{verbum|eledmac2}{1-1}
\indexentry{nihil|eledmac3}{1-2}
\indexentry{lux|eledmac4}{1-3}
\indexentry{homo|eledmac5}{1-5}
\indexentry{deus|eledmac6}{1-5}
\indexentry{mundus|eledmac7}{1-7}


The eledmac-markup-attr.xdy:
(define-attributes ("eledmac1"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&1}{{"
 :close "}}"
 :attr "eledmac1"
 ) 
(define-attributes ("eledmac2"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&2}{{"
 :close "}}"
 :attr "eledmac2"
 ) 
(define-attributes ("eledmac3"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&3}{{"
 :close "}}"
 :attr "eledmac3"
 ) 
(define-attributes ("eledmac4"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&4}{{"
 :close "}}"
 :attr "eledmac4"
 ) 
(define-attributes ("eledmac5"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&5}{{"
 :close "}}"
 :attr "eledmac5"
 ) 
(define-attributes ("eledmac6"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&6}{{"
 :close "}}"
 :attr "eledmac6"
 ) 
(define-attributes ("eledmac7"))
   (markup-locref
 :depth 1
 :open "\hyperlink{$&7}{{"
 :close "}}"
 :attr "eledmac7"
 )

**Comment by maieul** [comment] 2015-05-06 16:39
and the error message?  the problem is only with \indexentry{homo|eledmac5}{1-5} ?

its seems it is more a problem of texdindy on your installation than of eledmac.

**Comment by sonator** [comment] 2015-05-06 16:50
Yes, the problem is only with \indexentry{homo|eledmac5}{1-5}.

The "normal" xindy warning for all entries is: 
location-reference "1-1" did match multiple location-classes! (taking first one), but the result is okay.

The warning concerning eledmac5 is: 
unknown attribute `eledmac5'! (ignored)

I start xindy on the command line as follows: 
xindy path verb.idx -C utf8 -L german-duden -M texindy -M meinstil -o path verb.ind

PS:
The indices in not numbered texts are working correctly with the same settings.

**Comment by maieul** [comment] 2015-05-06 20:57
and what do yo have in meinstil.xdy?

**Comment by sonator** [comment] 2015-05-07 09:09
This is the content of meinstil.xdy, used yesterday. 

Now, I am guessing the actual problem! The command (require "c:\l\03\xelatex\test2\eledmac-markup-attr.xdy") calls the wrong file, when xelatex is working in an other folder, isn't it? 

Just now I have made a test in the folder test2 -- successfully, without warnings. Xindy is happy, and I am too. 

Pro Iuppiter, mea propria culpa, sorry, sorry! 

How do I call the current eledmac-markup-attr.xdy correctly, so that it works, when I change the folder? 


;;ruft Vorgaben von eledmac auf
(require "c:\l\03\xelatex\test2\eledmac-markup-attr.xdy")

;;automatische Module verwenden
(require "texindy.xdy")
(require "page-ranges.xdy")
(require "german-sty.xdy")

;;;Vorgabe wg eledmac
(define-location-class "eledmac" ("arabic-numbers" :sep"-" "arabic-numbers") :hierdepth 2)
(define-location-class "lines" ("arabic-numbers" :sep "-" "arabic-numbers"))

(markup-range :sep "-")
(markup-locref-list :open " (" :sep "," :close ") " :depth 1 :class "eledmac" )

(markup-letter-group  :open-head "\hfill\textbf{" :close-head "}\hfill\nopagebreak" ) 
(markup-locclass-list :open " \dotfill\ " )

**Comment by maieul** [comment] 2015-05-07 18:41
> How do I call the current eledmac-markup-attr.xdy correctly, so that it works, when I change the folder? 

I don't understand your question. I think you should ask on tex.stackexchange, as it is a xindy problem. In any case I close the issue.

**Closed by maieul** 2015-05-07 18:41 UTC
