### ISSUE TITLE
KOMA-Script and reledpar/astanza

### ISSUE THREAD

**Issue by Irgend-Wer** [maieul/ledmac#850] opened 2020-03-06 23:11 UTC
# Version
Package: reledmac 2020/02/04 v2.32.4 typesetting critical editions
Package: reledpar 2019/11/04 v2.22.4 reledmac extension for parallel texts

# TeX Engine
This is LuaTeX, Version 1.10.0 (TeX Live 2019)  (format=lualatex 2020.3.2)

# Regression
none

# Description
I am not able to use \subsubsection{...} within the astanza environment in the right and proper way. It causes a pagebreak after the first line of the stanza. (I think it looks like a additional linebreak either...)
Via the list of reledmac/-par users the maintainer (Maïeul Rouquette) gave me the following information:
-- That is linked to the scrbook class. (With standard LaTeX classes, it works fine. scrbook and Koma script redefine multiple things, which makes it more complex to integrate with reledmac)
-- Maïeul Rouquette has found the origin of the problem. Solving it implies modification
of Komascript. I has send an email to the Komascript team. 

Does the problem happen only when combined with certain packages?
-- It occurs in combination with Koma-Skript.
Does the problem happen both in parallel typesetting and normal typesetting?
-- I did not yet have tested it in normal typesetting.

# Minimal Working Example

```latex
\documentclass{scrbook}
\usepackage[series={A,B},noend,noeledsec]{reledmac}
\usepackage{reledpar}
\setstanzaindents{1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}

\parindent=0pt

\begin{document}
\begin{pages}
\beginnumbering
\begin{Leftside}
\begin{astanza}[\subsubsection{Text}] XXX XXX XXX. &
XXX \& \end{astanza}
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\begin{astanza}[\subsubsection{Translation}] XXX. &
XXX \& \end{astanza}
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
````

# Workaround

Maïeul Rouquette says it seems to be related to the way Koma-Script manage internal hooks.
What you can do is to disable them temporally before using \Pages, using
code like this:

```latex
\let\oldExecuteDoHook\ExecuteDoHook
\renewcommand{\ExecuteDoHook}[1]{}
\Pages
\let\ExecuteDoHook\oldExecuteDoHook
```
Thanks for this workaround!

[pagebreak.pdf](https://github.com/maieul/ledmac/files/4300900/pagebreak.pdf)
[pagebreak.log](https://github.com/maieul/ledmac/files/4300901/pagebreak.log)

**Comment by maieul** [comment] 2020-03-07 13:28
I have send an email to the Koma Script team. Mark have looked on the code, and change some internal trick.

Here a copy of this email.

> Unfortunately adding an extra group would break the DoHook mechanism, because 
> then the hook code is processed inside an this extra group. For the mechanism 
> it is a must, that the expansion of the hook is done in the same group as the 
> \ExecuteDoHook. Otherwise the hooks wouldn't be able to modify internal 
> parameters, e.g., of the \subsubsection. Maybe even tagging, which was the 
> original motivation for the mechanism, wouldn't be able to use the mechanism.
> 
> However, I've changed it in another way, so the problem should be solved with 
> KOMA-Script 3.30 and the current pre-release (see <https://www.komascript.de/
> current>).

As the problem is on Koma Script, and as Koma Script 3.30 will solve it, I close this issue.

**Comment by Irgend-Wer** [comment] 2020-03-07 14:20
Thanks a lot for your efforts in this matter.

**Comment by Irgend-Wer** [comment] 2020-03-07 15:40
I tested it via
`tlmgr install --reinstall --repository https://www.komascript.de/repository/texlive/2019 koma-script`
and it worked!
Again: Thank you very much!

**Closed** 2020-03-07 17:14 UTC
