### ISSUE TITLE
paragraph footnotes do not reset \parfillskip

### ISSUE THREAD

**Issue by u-fischer** [maieul/ledmac#963] opened 2024-03-06 16:53 UTC
# Version
2022/02/04 v2.39.1

# TeX Engine

Doesn't matter

# Regression

I think it is old

# Description

If `\parfillskip` is set to 0pt when the output routine is called, paragraph footnotes stretch their last line

# Minimal Working Example

```latex
\documentclass{book}
\usepackage{reledmac}
\textheight=3cm
\textwidth=4.5cm

\arrangementX[A]{paragraph}
\usepackage{lipsum}
\begin{document}
\centering % or \raggedleft
some text\footnoteA{\lipsum*[1][1-2]}
\end{document}
```

![image](https://github.com/maieul/ledmac/assets/4047173/5c8b028e-df7a-4388-81ac-f754eb0ea57a)

# Workaround
Adding `\@parboxrestore` or less agressive `\parfillskip=0pt plus 1fil` to `\parafootstartX` seems to work. I didn't check the other footnote types, but assume that the setting is missing in more places.

~~~~
\documentclass{book}
\usepackage{reledmac}
\textheight=3cm
\textwidth=4.5cm
\makeatletter
\renewcommand*{\parafootstartX}[1]{%
    \ifdimequal{0pt}{\prenotesX@}{}%
      {%
      \iftoggle{prenotesX@}{%
            \togglefalse{prenotesX@}%
            \skip\csname footins#1\endcsname=%
              \glueexpr\csuse{prenotesX@}+\csuse{afterruleX@#1}\relax%
            }%
          {}%
      }%
  \leftskip=\z@
  \rightskip=\z@
  %\@parboxrestore% <---------this
  \parfillskip=0pt plus 1fil %<-------- or this  
  \setparindentX{#1}%
  \vskip\skip\@nameuse{footins#1}%
  \setnoteswidthliketwocolumnsX@{#1}%
  \setnotesXpositionliketwocolumns@{#1}%
  \print@footnoteXrule{#1}%
  }

\arrangementX[A]{paragraph}
\usepackage{lipsum}
\begin{document}
\centering % or \raggedleft
some text\footnoteA{\lipsum*[1][1-2]}
\end{document}
~~~~

![image](https://github.com/maieul/ledmac/assets/4047173/eb9676fe-e276-472f-a307-eef52ec3e2be)

**Comment by maieul** [comment] 2024-03-06 17:04
Well, normally, paragraphed footnote are for small chunk of text, and so this omission should not have any consequence. I don't know which would be the best solution, in order to avoid breaking historical compatibility...

**Comment by u-fischer** [comment] 2024-03-06 17:10
I used a longer footnote in the example, but you would get the same problem with one or more short paragraph footnote. E.g. try with 

~~~~
\begin{document}
\centering % or \raggedleft
some text\footnoteA{some text}
some text\footnoteA{some text}
some text\footnoteA{some text}
some text\footnoteA{some text}
\end{document}
~~~~

![image](https://github.com/maieul/ledmac/assets/4047173/1db7cd7c-ba70-45a4-8237-dd8bfec99918)

or 

~~~~
\begin{document}
\centering % or \raggedleft
some text\footnoteA{some text}
\end{document}
~~~~

![image](https://github.com/maieul/ledmac/assets/4047173/d937b2f3-b826-40c2-887a-ca38e0c13862)

**Comment by maieul** [comment] 2024-03-06 17:22
Thanks,

I was not looking on reledmac and tex world since many time, and I forget what `\parfillskip` does exactly. But re-reading your text, I also see that the problem happens only when we deal with centering or ragged right text. So that why I didn't remember such bug in the past.

anyway, I thank your proposal `\parfillskip=0pt plus 1fil` is better. Maybe next week on the trip I will have time to do more test for other footnote series and do a fix.

**Comment by u-fischer** [comment] 2024-03-13 10:00
Two column footnotes are affected too. There I fixed it by extending \footsplitskips.

**Comment by maieul** [comment] 2024-04-27 13:44
dear @u-fischer ; I tried to reproduce bug with twocolumn and threcolumn footnote, but was not able. COuld you provide a MWE?

**Comment by u-fischer** [comment] 2024-04-28 22:10
E.g. 

~~~~
\documentclass{book}
\usepackage{reledmac}
\arrangementX[B]{twocol}
\colalignX[B]{}
\usepackage{etoolbox}
\makeatletter
%\patchcmd\footsplitskips
%  {\rightskip=\z@skip}
%  {\rightskip=\z@skip \parfillskip=0pt plus 1fil }
%  {}{\fail}

\begin{document}

\raggedleft blub 
\footnoteB{some longer some longer some longer some longer}
\footnoteB{some longer}

\end{document}
~~~~

![image](https://github.com/maieul/ledmac/assets/4047173/d11f1cb9-7436-47e8-929a-89638d51bc74)

**Comment by maieul** [comment] 2024-05-01 15:37
Well, that is because you use `\colalignX[B]{}` and so delete the default `\raggedright`.

**Comment by maieul** [comment] 2024-05-01 15:58
Please try the branch issue_963, which implement your fix, but also for critical footnote, not only familiar ones.

**Comment by maieul** [comment] 2024-05-10 20:12
Will be released tomorrow night

**Closed** 2024-05-11 08:48 UTC
